using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class pC : MonoBehaviour
{
    private Rigidbody2D rb2D;
    private Vector2 move;
    float speed;

    // Start is called before the first frame update
    void Start()
    {
        rb2D = GetComponent<Rigidbody2D>();
        speed = 900f;
    }

    // Update is called once per frame
    void Update()
    {
        move = new Vector2(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical"));
    }

    private void FixedUpdate()
    {
       rb2D.AddForce(move * speed * Time.fixedDeltaTime);
       // rb2D.MovePosition(rb2D.position + move * speed * Time.fixedDeltaTime);
    }
}
